# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial

language: python
python: 
    - 2.7
    - 3.8

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_Brian2    
    - OMV_ENGINE=jNeuroML_PyNN_NEURON
    #- OMV_ENGINE=Brian   # Brain1 won't run on py3
    - OMV_ENGINE=Brian2        
    - OMV_ENGINE=PyLEMS_NeuroML2


before_install:
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-sympy

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    - omv list-engines -V
    
    
    

